// cpp-batch2.js : C++ sections 07-12 (challenges, strings, conditionals, loops, indices)
window.SECTIONS = window.SECTIONS || {};
Object.assign(window.SECTIONS, {
cpp07: [
{id:"cpp07a",t:"Your First Challenge",d:1,p:"Read three ints. Print their integer average (sum divided by 3, truncated).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a,b,c; cin >> a >> b >> c;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b,c;cin>>a>>b>>c;cout<<(a+b+c)/3;return 0;}",tests:[{in:"3 4 5",out:"4"},{in:"1 2 3",out:"2"}],h:["Integer division truncates automatically.","Parentheses around the sum."]},
{id:"cpp07b",t:"Buy Candy II",d:1,p:"Candy costs 3 coins. Read coins; print candies bought and coins left over, space separated.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int c; cin >> c;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int c;cin>>c;cout<<c/3<<\" \"<<c%3;return 0;}",tests:[{in:"10",out:"3 1"},{in:"9",out:"3 0"}],h:["Division and modulo pair again."]},
{id:"cpp07c",t:"Hand Shakes",d:2,p:"n people each shake hands with everyone else exactly once. Read n, print total handshakes.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;cout<<n*(n-1)/2;return 0;}",tests:[{in:"4",out:"6"},{in:"1",out:"0"}],h:["Each pair counted once.","n*(n-1)/2"]},
{id:"cpp07d",t:"Last Two Digit Sum",d:2,p:"Read an int with at least two digits. Print the sum of its last two digits.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;cout<<n%10+(n/10)%10;return 0;}",tests:[{in:"1234",out:"7"},{in:"99",out:"18"}],h:["n%10 is the last digit.","(n/10)%10 is the second-to-last."]},
{id:"cpp07e",t:"Digit Count",d:2,p:"Read a positive int. Print how many digits it has, using a loop (no strings).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int c=0;while(n>0){n/=10;c++;}cout<<c;return 0;}",tests:[{in:"12345",out:"5"},{in:"7",out:"1"}],h:["Divide by 10 until zero, counting."]},
],
cpp08: [
{id:"cpp08a",t:"Read A Word",d:1,p:"Read one word into a string. Print: Hello, <word>!",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; cin >> s;\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;cout<<\"Hello, \"<<s<<\"!\";return 0;}",tests:[{in:"Ana",out:"Hello, Ana!"}],h:["cin >> reads one whitespace-separated word."]},
{id:"cpp08b",t:"Whole Line Length",d:1,p:"Read a FULL line (with spaces) and print its length.",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s;\n    // read the whole line\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;getline(cin,s);cout<<s.size();return 0;}",tests:[{in:"hello world",out:"11"},{in:"a",out:"1"}],h:["getline(cin, s) grabs the whole line.","s.size() or s.length()."]},
{id:"cpp08c",t:"First And Last",d:2,p:"Read a word. Print its first and last characters with no space between (a 1-letter word prints its letter twice).",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; cin >> s;\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;cout<<s[0]<<s[s.size()-1];return 0;}",tests:[{in:"murim",out:"mm"},{in:"a",out:"aa"}],h:["s[0] and s[s.size()-1]."]},
{id:"cpp08d",t:"Join With Dash",d:1,p:"Read two words. Print them joined by a single dash.",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string a, b; cin >> a >> b;\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string a,b;cin>>a>>b;cout<<a+\"-\"+b;return 0;}",tests:[{in:"iron fist",out:"iron-fist"}],h:["Strings concatenate with +."]},
{id:"cpp08e",t:"Same Or Diff",d:1,p:"Read two words. Print 'same' if equal, else 'diff'.",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string a, b; cin >> a >> b;\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string a,b;cin>>a>>b;cout<<(a==b?\"same\":\"diff\");return 0;}",tests:[{in:"qi qi",out:"same"},{in:"qi ki",out:"diff"}],h:["== works directly on std::string."]},
{id:"cpp08f",t:"Shout It",d:2,p:"Read a word (letters only). Print it uppercased, converting with character math (lowercase letters are 32 above uppercase).",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; cin >> s;\n    for (int i = 0; i < (int)s.size(); i++) {\n        // convert s[i] if lowercase\n    }\n    cout << s;\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;for(int i=0;i<(int)s.size();i++){if(s[i]>='a'&&s[i]<='z')s[i]-=32;}cout<<s;return 0;}",tests:[{in:"abC",out:"ABC"},{in:"HI",out:"HI"}],h:["Check 'a' <= c <= 'z'.","Subtract 32 to uppercase."]},
{id:"cpp08g",t:"Count Vowels",d:2,p:"Read a lowercase word. Print how many vowels (a e i o u) it contains.",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s; cin >> s;\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){string s;cin>>s;int c=0;for(int i=0;i<(int)s.size();i++){char x=s[i];if(x=='a'||x=='e'||x=='i'||x=='o'||x=='u')c++;}cout<<c;return 0;}",tests:[{in:"firmware",out:"3"},{in:"sky",out:"0"}],h:["Loop chars, OR the five checks."]},
],
cpp09: [
{id:"cpp09a",t:"Leap Year",d:2,p:"Read a year. Print 'leap' if divisible by 4 and not by 100, OR divisible by 400. Else 'not leap'.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int y; cin >> y;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int y;cin>>y;if((y%4==0&&y%100!=0)||y%400==0)cout<<\"leap\";else cout<<\"not leap\";return 0;}",tests:[{in:"2024",out:"leap"},{in:"1900",out:"not leap"},{in:"2000",out:"leap"}],h:["Translate the rule literally with && and ||.","1900 is the trap: divisible by 100, not 400."]},
{id:"cpp09b",t:"Triangle Type",d:2,p:"Read three side lengths (a valid triangle). Print equilateral, isosceles, or scalene.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a,b,c; cin >> a >> b >> c;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b,c;cin>>a>>b>>c;if(a==b&&b==c)cout<<\"equilateral\";else if(a==b||b==c||a==c)cout<<\"isosceles\";else cout<<\"scalene\";return 0;}",tests:[{in:"3 3 3",out:"equilateral"},{in:"3 3 5",out:"isosceles"},{in:"3 4 5",out:"scalene"}],h:["Check all-equal first, then any-two-equal."]},
{id:"cpp09c",t:"Which Quadrant",d:2,p:"Read x and y (both non-zero). Print the quadrant number 1-4.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int x,y; cin >> x >> y;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int x,y;cin>>x>>y;if(x>0&&y>0)cout<<1;else if(x<0&&y>0)cout<<2;else if(x<0&&y<0)cout<<3;else cout<<4;return 0;}",tests:[{in:"3 -2",out:"4"},{in:"-1 -1",out:"3"},{in:"2 5",out:"1"}],h:["Signs of x and y decide it."]},
{id:"cpp09d",t:"Sort Three",d:3,p:"Read three ints. Print them in ascending order space separated, using only if statements and swaps (no arrays, no sort).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a,b,c; cin >> a >> b >> c;\n\n    cout << a << \" \" << b << \" \" << c;\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b,c;cin>>a>>b>>c;int t;if(a>b){t=a;a=b;b=t;}if(b>c){t=b;b=c;c=t;}if(a>b){t=a;a=b;b=t;}cout<<a<<\" \"<<b<<\" \"<<c;return 0;}",tests:[{in:"3 1 2",out:"1 2 3"},{in:"9 9 1",out:"1 9 9"},{in:"1 2 3",out:"1 2 3"}],h:["Three compare-and-swaps: (a,b), (b,c), (a,b) again.","That's a tiny bubble sort."]},
{id:"cpp09e",t:"Cinema Discount",d:1,p:"Read an age. Print 'discount' if under 12 or 65 and over, else 'full'.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a; cin >> a;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a;cin>>a;if(a<12||a>=65)cout<<\"discount\";else cout<<\"full\";return 0;}",tests:[{in:"8",out:"discount"},{in:"30",out:"full"},{in:"65",out:"discount"}],h:["|| combines the two age rules."]},
],
cpp10: [
{id:"cpp10a",t:"Sum 1 To n",d:1,p:"Read n. Print the sum 1+2+...+n using a for loop.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int s=0;for(int i=1;i<=n;i++)s+=i;cout<<s;return 0;}",tests:[{in:"5",out:"15"},{in:"1",out:"1"}],h:["Loop i from 1 to n inclusive."]},
{id:"cpp10b",t:"Factorial",d:2,p:"Read n (0 <= n <= 12). Print n! (0! is 1).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int f=1;for(int i=2;i<=n;i++)f*=i;cout<<f;return 0;}",tests:[{in:"5",out:"120"},{in:"0",out:"1"}],h:["Start the product at 1.","Loop can start at 2."]},
{id:"cpp10c",t:"Powers Of Two",d:2,p:"Read n. Print all powers of two <= n, space separated, starting from 1.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int p=1;bool first=true;while(p<=n){if(!first)cout<<\" \";cout<<p;first=false;p*=2;}return 0;}",tests:[{in:"20",out:"1 2 4 8 16"},{in:"1",out:"1"}],h:["Multiply by 2 each round.","Handle the space-between formatting."]},
{id:"cpp10d",t:"Digit Reverse",d:2,p:"Read a positive int. Print the number with its digits reversed (1200 becomes 21).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int r=0;while(n>0){r=r*10+n%10;n/=10;}cout<<r;return 0;}",tests:[{in:"123",out:"321"},{in:"1200",out:"21"}],h:["Peel digits with %10, build r with r*10+digit."]},
{id:"cpp10e",t:"Collatz Steps",d:3,p:"Read n>=1. Repeatedly: if even n/=2, else n=3n+1, until n is 1. Print how many steps it took (n=1 takes 0).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int c=0;while(n!=1){if(n%2==0)n/=2;else n=3*n+1;c++;}cout<<c;return 0;}",tests:[{in:"6",out:"8"},{in:"1",out:"0"}],h:["while (n != 1), count each transform.","Trace 6 by hand to trust your loop."]},
{id:"cpp10f",t:"GCD (Euclid)",d:2,p:"Read two positive ints. Print their greatest common divisor using Euclid's algorithm.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a,b; cin >> a >> b;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b;cin>>a>>b;while(b!=0){int t=b;b=a%b;a=t;}cout<<a;return 0;}",tests:[{in:"12 18",out:"6"},{in:"7 5",out:"1"}],h:["while b != 0: a,b = b, a%b.","This exact loop shows up in interviews forever."]},
],
cpp11: [
{id:"cpp11a",t:"Pos / Neg / Zero",d:2,p:"Read n, then n ints. Print three counts: positives negatives zeros, space separated.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int p=0,q=0,z=0;for(int i=0;i<n;i++){int x;cin>>x;if(x>0)p++;else if(x<0)q++;else z++;}cout<<p<<\" \"<<q<<\" \"<<z;return 0;}",tests:[{in:"5\n3 -1 0 7 -2",out:"2 2 1"},{in:"1\n0",out:"0 0 1"}],h:["Three counters, one if/else-if/else."]},
{id:"cpp11b",t:"FizzBuzz Range",d:2,p:"Read n. For 1..n print each on its own line: Fizz (div 3), Buzz (div 5), FizzBuzz (both), else the number.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;for(int i=1;i<=n;i++){if(i%15==0)cout<<\"FizzBuzz\\n\";else if(i%3==0)cout<<\"Fizz\\n\";else if(i%5==0)cout<<\"Buzz\\n\";else cout<<i<<\"\\n\";}return 0;}",tests:[{in:"5",out:"1\n2\nFizz\n4\nBuzz"},{in:"15",out:"1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz"}],h:["Your single-value FizzBuzz inside a for loop."]},
{id:"cpp11c",t:"Sum Of Evens",d:1,p:"Read n. Print the sum of even numbers from 1 to n.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int s=0;for(int i=2;i<=n;i+=2)s+=i;cout<<s;return 0;}",tests:[{in:"10",out:"30"},{in:"1",out:"0"}],h:["Step the loop by 2."]},
{id:"cpp11d",t:"First Multiple Above",d:2,p:"Read n and k. Print the smallest multiple of k that is strictly greater than n.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n,k; cin >> n >> k;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n,k;cin>>n>>k;int m=k;while(m<=n)m+=k;cout<<m;return 0;}",tests:[{in:"10 3",out:"12"},{in:"9 3",out:"12"}],h:["Keep adding k while m <= n.","9 3 gives 12, not 9: strictly greater."]},
{id:"cpp11e",t:"Prime Check",d:3,p:"Read n >= 2. Print 'prime' or 'not prime'. Only test divisors while i*i <= n.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;bool p=true;for(int i=2;i*i<=n;i++){if(n%i==0){p=false;break;}}cout<<(p?\"prime\":\"not prime\");return 0;}",tests:[{in:"13",out:"prime"},{in:"15",out:"not prime"},{in:"2",out:"prime"}],h:["Divisors pair up around sqrt(n), so i*i<=n suffices.","break as soon as one divides."]},
{id:"cpp11f",t:"Password Attempts",d:2,p:"First line: the secret int. Then ints follow one at a time; the secret is guaranteed to appear. Print how many reads it took to hit it.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int secret; cin >> secret;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int s;cin>>s;int g,c=0;while(cin>>g){c++;if(g==s)break;}cout<<c;return 0;}",tests:[{in:"7\n3 5 7",out:"3"},{in:"1\n1",out:"1"}],h:["while (cin >> g) reads until it can't.","Count every read, break on match."]},
],
cpp12: [
{id:"cpp12a",t:"Print With Indices",d:1,p:"Read n, then n ints into an array. Print one per line as index:value (like 0:10).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];for(int i=0;i<n;i++)cout<<i<<\":\"<<a[i]<<\"\\n\";return 0;}",tests:[{in:"3\n10 20 30",out:"0:10\n1:20\n2:30"}],h:["Two loops: fill, then print."]},
{id:"cpp12b",t:"Number Index In Array",d:2,p:"Read n, the array, then a target. Print the FIRST index holding the target, or -1.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n    for (int i=0;i<n;i++) cin >> a[i];\n    int t; cin >> t;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];int t;cin>>t;int idx=-1;for(int i=0;i<n;i++){if(a[i]==t){idx=i;break;}}cout<<idx;return 0;}",tests:[{in:"4\n5 8 8 2\n8",out:"1"},{in:"3\n1 2 3\n9",out:"-1"}],h:["break on first hit or you'll report the last.","Default answer -1 before the loop."]},
{id:"cpp12c",t:"Lower Bound Index",d:3,p:"Read n, a SORTED array, then target t. Print the first index i where a[i] >= t; if none, print n.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n    for (int i=0;i<n;i++) cin >> a[i];\n    int t; cin >> t;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];int t;cin>>t;int idx=n;for(int i=0;i<n;i++){if(a[i]>=t){idx=i;break;}}cout<<idx;return 0;}",tests:[{in:"4\n1 3 5 7\n4",out:"2"},{in:"3\n1 2 3\n9",out:"3"}],h:[">= not ==: 4 isn't in the array but 5 is where it would go.","This is what std::lower_bound does; here it's a linear scan."]},
{id:"cpp12d",t:"Boost Even Indices",d:2,p:"Read n and the array. Add 1 to every element at an EVEN index, then print the array space separated.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n    for (int i=0;i<n;i++) cin >> a[i];\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];for(int i=0;i<n;i+=2)a[i]++;for(int i=0;i<n;i++)cout<<a[i]<<(i<n-1?\" \":\"\");return 0;}",tests:[{in:"4\n5 5 5 5",out:"6 5 6 5"},{in:"1\n9",out:"10"}],h:["Even INDEX, not even value.","Loop i += 2."]},
{id:"cpp12e",t:"Get Full Names",d:2,p:"Read n, then n lines each containing 'first last'. Print each as 'last, first' on its own line.",s:"#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\n#include <string>\nusing namespace std;\nint main(){int n;cin>>n;for(int i=0;i<n;i++){string f,l;cin>>f>>l;cout<<l<<\", \"<<f<<\"\\n\";}return 0;}",tests:[{in:"2\nBruce Lee\nIp Man",out:"Lee, Bruce\nMan, Ip"}],h:["cin >> f >> l splits on the space for you."]},
{id:"cpp12f",t:"Reverse In Place",d:2,p:"Read n and the array. Reverse it IN PLACE by swapping a[i] with a[n-1-i], then print space separated.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n    for (int i=0;i<n;i++) cin >> a[i];\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];for(int i=0;i<n/2;i++){int t=a[i];a[i]=a[n-1-i];a[n-1-i]=t;}for(int i=0;i<n;i++)cout<<a[i]<<(i<n-1?\" \":\"\");return 0;}",tests:[{in:"4\n1 2 3 4",out:"4 3 2 1"},{in:"5\n1 2 3 4 5",out:"5 4 3 2 1"}],h:["Only loop to n/2 or you undo your work.","Classic two-pointer swap."]},
{id:"cpp12g",t:"Second Largest",d:3,p:"Read n >= 2 and the array. Print the second largest value (ties allowed: for 5 5 2 the answer is 5).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n    for (int i=0;i<n;i++) cin >> a[i];\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];int m1,m2;if(a[0]>=a[1]){m1=a[0];m2=a[1];}else{m1=a[1];m2=a[0];}for(int i=2;i<n;i++){if(a[i]>=m1){m2=m1;m1=a[i];}else if(a[i]>m2)m2=a[i];}cout<<m2;return 0;}",tests:[{in:"4\n3 9 4 7",out:"7"},{in:"3\n5 5 2",out:"5"}],h:["Track top two, seeded from the first two elements.","New max demotes the old max to second."]},
]
});
