// cpp-core.js : populated C++ sections (lang: cpp runs via JSCPP interpreter / Judge0)
// Exercise: {id,t:title,d:diff,p:prompt,s:starter,sol:solution,tests:[{in,out}],h:[hints]}
// tests compare trimmed stdout given stdin `in`.
window.SECTIONS = window.SECTIONS || {};
Object.assign(window.SECTIONS, {
cpp01: [
{id:"cpp01a",t:"Hello, Murim",d:1,p:"Print exactly: Hello, World!",s:"#include <iostream>\nusing namespace std;\nint main() {\n    // your code\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){cout<<\"Hello, World!\";return 0;}",tests:[{in:"",out:"Hello, World!"}],h:["cout << sends text to the console.","Strings need double quotes."]},
{id:"cpp01b",t:"Two Lines",d:1,p:"Print two lines: first 'C++' then 'is fast'.",s:"#include <iostream>\nusing namespace std;\nint main() {\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){cout<<\"C++\\n\"<<\"is fast\";return 0;}",tests:[{in:"",out:"C++\nis fast"}],h:["\\n inside a string starts a new line.","You can chain: cout << a << b;"]},
{id:"cpp01c",t:"Comments Don't Run",d:1,p:"The starter prints WRONG. Comment out the bad line so only 'clean' prints.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"WRONG\\n\";\n    cout << \"clean\";\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){//cout<<\"WRONG\\n\";\ncout<<\"clean\";return 0;}",tests:[{in:"",out:"clean"}],h:["// comments out one line."]},
{id:"cpp01d",t:"Chained Output",d:1,p:"Print: Level 9 warrior (using three separate << pieces: 'Level ', 9, ' warrior').",s:"#include <iostream>\nusing namespace std;\nint main() {\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){cout<<\"Level \"<<9<<\" warrior\";return 0;}",tests:[{in:"",out:"Level 9 warrior"}],h:["Numbers don't need quotes.","cout << \"Level \" << 9 << ...;"]},
{id:"cpp01e",t:"Fix The Build",d:2,p:"This code has 2 compile errors (missing semicolon, wrong stream name). Fix it to print: fixed",s:"#include <iostream>\nusing namespace std;\nint main() {\n    count << \"fixed\"\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){cout<<\"fixed\";return 0;}",tests:[{in:"",out:"fixed"}],h:["It's cout, not count.","Every statement ends with ;"]},
],
cpp02: [
{id:"cpp02a",t:"Declare And Print",d:1,p:"Create an int named qi with value 42 and print it.",s:"#include <iostream>\nusing namespace std;\nint main() {\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int qi=42;cout<<qi;return 0;}",tests:[{in:"",out:"42"}],h:["int name = value;"]},
{id:"cpp02b",t:"Types Tour",d:1,p:"Print on 3 lines: an int 7, a double 3.5, a char 'H'.",s:"#include <iostream>\nusing namespace std;\nint main() {\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a=7;double b=3.5;char c='H';cout<<a<<\"\\n\"<<b<<\"\\n\"<<c;return 0;}",tests:[{in:"",out:"7\n3.5\nH"}],h:["char uses single quotes: 'H'."]},
{id:"cpp02c",t:"Read Input",d:1,p:"Read one int from input and print: You entered X",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int x;\n    // read x, then print\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int x;cin>>x;cout<<\"You entered \"<<x;return 0;}",tests:[{in:"5",out:"You entered 5"},{in:"-3",out:"You entered -3"}],h:["cin >> x; reads into x."]},
{id:"cpp02d",t:"Swap Two Variables",d:2,p:"Read two ints a and b, swap them, print 'a b' after the swap (space separated).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a, b;\n    cin >> a >> b;\n\n    cout << a << \" \" << b;\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b;cin>>a>>b;int t=a;a=b;b=t;cout<<a<<\" \"<<b;return 0;}",tests:[{in:"1 2",out:"2 1"},{in:"9 9",out:"9 9"}],h:["Use a third temp variable.","t=a; a=b; b=t;"]},
{id:"cpp02e",t:"const Means It",d:2,p:"Declare const int MAX_HP = 100; then print: MAX_HP is 100 (using the variable, not a literal 100 in the cout).",s:"#include <iostream>\nusing namespace std;\nint main() {\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){const int MAX_HP=100;cout<<\"MAX_HP is \"<<MAX_HP;return 0;}",tests:[{in:"",out:"MAX_HP is 100"}],h:["const int NAME = value;"]},
],
cpp03: [
{id:"cpp03a",t:"Arithmetic Operators",d:1,p:"Read two ints, print their sum, difference, and product on 3 lines.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a, b;\n    cin >> a >> b;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b;cin>>a>>b;cout<<a+b<<\"\\n\"<<a-b<<\"\\n\"<<a*b;return 0;}",tests:[{in:"6 3",out:"9\n3\n18"},{in:"2 5",out:"7\n-3\n10"}],h:["+ - * work directly in cout."]},
{id:"cpp03b",t:"Area Of Rectangle",d:1,p:"Read width and height (ints), print the area.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int w, h;\n    cin >> w >> h;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int w,h;cin>>w>>h;cout<<w*h;return 0;}",tests:[{in:"4 5",out:"20"},{in:"7 3",out:"21"}],h:["area = w * h"]},
{id:"cpp03c",t:"Find Discount",d:2,p:"Read a price (double) and a discount percent (int). Print the discount amount (price*percent/100). Trust default formatting.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    double price; int pct;\n    cin >> price >> pct;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){double price;int pct;cin>>price>>pct;cout<<price*pct/100;return 0;}",tests:[{in:"200 10",out:"20"},{in:"50 50",out:"25"}],h:["Multiply first, then divide by 100.","price is double so the math stays double."]},
{id:"cpp03d",t:"Operator Precedence",d:2,p:"Without changing the numbers, add ONE pair of parentheses so this prints 20 instead of 14: cout << 2 + 3 * 4;",s:"#include <iostream>\nusing namespace std;\nint main() {\n    cout << 2 + 3 * 4;\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){cout<<(2+3)*4;return 0;}",tests:[{in:"",out:"20"}],h:["* binds tighter than + by default."]},
{id:"cpp03e",t:"Hours And Mins Into Seconds",d:1,p:"Read hours and minutes (ints). Print total seconds.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int h, m;\n    cin >> h >> m;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int h,m;cin>>h>>m;cout<<h*3600+m*60;return 0;}",tests:[{in:"1 30",out:"5400"},{in:"0 2",out:"120"}],h:["1 hour = 3600 s, 1 min = 60 s."]},
{id:"cpp03f",t:"Floor Division & Modulo",d:2,p:"Read total minutes. Print 'H hours M minutes' using integer division and modulo.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int total;\n    cin >> total;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int t;cin>>t;cout<<t/60<<\" hours \"<<t%60<<\" minutes\";return 0;}",tests:[{in:"135",out:"2 hours 15 minutes"},{in:"59",out:"0 hours 59 minutes"}],h:["int/int truncates: 135/60 = 2.","% gives the remainder."]},
{id:"cpp03g",t:"Free Coffee Cups",d:2,p:"A cafe gives 1 free coffee per 5 stamps. Read stamp count; print free coffees earned and stamps left over, space separated.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int stamps;\n    cin >> stamps;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int s;cin>>s;cout<<s/5<<\" \"<<s%5;return 0;}",tests:[{in:"12",out:"2 2"},{in:"4",out:"0 4"}],h:["Same tools as the time problem: / and %."]},
{id:"cpp03h",t:"Augmented & Increment",d:2,p:"Start with int x = 10. Apply in order: x += 5; x *= 2; x--; then print x.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int x = 10;\n\n    cout << x;\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int x=10;x+=5;x*=2;x--;cout<<x;return 0;}",tests:[{in:"",out:"29"}],h:["x += 5 means x = x + 5.","Work it by hand: 10 -> 15 -> 30 -> 29."]},
],
cpp04: [
{id:"cpp04a",t:"First Function",d:1,p:"Write a function greet() that prints 'ready'. Call it from main.",s:"#include <iostream>\nusing namespace std;\n\n// define greet here\n\nint main() {\n    greet();\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nvoid greet(){cout<<\"ready\";}\nint main(){greet();return 0;}",tests:[{in:"",out:"ready"}],h:["void name() { ... } above main."]},
{id:"cpp04b",t:"Parameters",d:1,p:"Write void shout(int n) that prints 'HA' n times on one line. main reads n and calls it.",s:"#include <iostream>\nusing namespace std;\n\n// define shout here\n\nint main() {\n    int n; cin >> n;\n    shout(n);\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nvoid shout(int n){for(int i=0;i<n;i++)cout<<\"HA\";}\nint main(){int n;cin>>n;shout(n);return 0;}",tests:[{in:"3",out:"HAHAHA"},{in:"1",out:"HA"}],h:["A for loop inside the function.","for(int i=0;i<n;i++)"]},
{id:"cpp04c",t:"Return Values",d:1,p:"Write int square(int x) returning x*x. main reads x, prints square(x).",s:"#include <iostream>\nusing namespace std;\n\n// define square here\n\nint main() {\n    int x; cin >> x;\n    cout << square(x);\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint square(int x){return x*x;}\nint main(){int x;cin>>x;cout<<square(x);return 0;}",tests:[{in:"6",out:"36"},{in:"-4",out:"16"}],h:["Return type int, use return."]},
{id:"cpp04d",t:"Max Of Three",d:2,p:"Write int max3(int a,int b,int c) returning the largest. main reads three ints and prints max3.",s:"#include <iostream>\nusing namespace std;\n\n// define max3 here\n\nint main() {\n    int a,b,c; cin >> a >> b >> c;\n    cout << max3(a,b,c);\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint max3(int a,int b,int c){int m=a;if(b>m)m=b;if(c>m)m=c;return m;}\nint main(){int a,b,c;cin>>a>>b>>c;cout<<max3(a,b,c);return 0;}",tests:[{in:"3 9 5",out:"9"},{in:"7 7 2",out:"7"}],h:["Track a running max m.","Two if statements are enough."]},
{id:"cpp04e",t:"Compose Functions",d:2,p:"Using your square from before plus int add(int,int), print add(square(a), square(b)) for input a b.",s:"#include <iostream>\nusing namespace std;\nint square(int x){ return x*x; }\n// define add here\n\nint main() {\n    int a,b; cin >> a >> b;\n    cout << add(square(a), square(b));\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint square(int x){return x*x;}\nint add(int x,int y){return x+y;}\nint main(){int a,b;cin>>a>>b;cout<<add(square(a),square(b));return 0;}",tests:[{in:"3 4",out:"25"}],h:["Functions can be arguments to functions."]},
{id:"cpp04f",t:"Buy Candy (Challenge)",d:2,p:"Candy costs 3 coins. Write int candies(int coins) returning how many you can buy. main reads coins, prints candies(coins).",s:"#include <iostream>\nusing namespace std;\n\nint main() {\n    int c; cin >> c;\n    cout << candies(c);\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint candies(int c){return c/3;}\nint main(){int c;cin>>c;cout<<candies(c);return 0;}",tests:[{in:"10",out:"3"},{in:"2",out:"0"}],h:["Integer division again.","Define the function ABOVE main or it won't compile."]},
],
cpp05: [
{id:"cpp05a",t:"If",d:1,p:"Read an int. If it's greater than 100, print 'big'. (Print nothing otherwise.)",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int x; cin >> x;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int x;cin>>x;if(x>100)cout<<\"big\";return 0;}",tests:[{in:"150",out:"big"},{in:"7",out:""}],h:["if (condition) { ... }"]},
{id:"cpp05b",t:"If / Else",d:1,p:"Read an int. Print 'even' or 'odd'.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int x; cin >> x;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int x;cin>>x;if(x%2==0)cout<<\"even\";else cout<<\"odd\";return 0;}",tests:[{in:"4",out:"even"},{in:"9",out:"odd"}],h:["x % 2 == 0 tests evenness.","== compares, = assigns. Classic bug."]},
{id:"cpp05c",t:"Else If Ladder",d:2,p:"Read a score 0-100. Print A (>=90), B (>=80), C (>=70), else F.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int s; cin >> s;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int s;cin>>s;if(s>=90)cout<<\"A\";else if(s>=80)cout<<\"B\";else if(s>=70)cout<<\"C\";else cout<<\"F\";return 0;}",tests:[{in:"91",out:"A"},{in:"80",out:"B"},{in:"42",out:"F"}],h:["Order matters: check highest first."]},
{id:"cpp05d",t:"Logical Operators",d:2,p:"Read age and hasTicket (0 or 1). Print 'enter' only if age >= 18 AND hasTicket is 1, else 'denied'.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int age, t; cin >> age >> t;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,t;cin>>a>>t;if(a>=18&&t==1)cout<<\"enter\";else cout<<\"denied\";return 0;}",tests:[{in:"20 1",out:"enter"},{in:"20 0",out:"denied"},{in:"15 1",out:"denied"}],h:["&& is AND, || is OR."]},
{id:"cpp05e",t:"Ternary",d:2,p:"Read two ints. Print the larger using the ternary operator (no if statement).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int a, b; cin >> a >> b;\n    // use  cond ? x : y\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int a,b;cin>>a>>b;cout<<(a>b?a:b);return 0;}",tests:[{in:"3 8",out:"8"},{in:"5 2",out:"5"}],h:["cout << (a > b ? a : b);","Parentheses around the ternary inside cout."]},
{id:"cpp05f",t:"FizzBuzz Single",d:2,p:"Read one int. Print Fizz if divisible by 3, Buzz if by 5, FizzBuzz if both, else the number.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;if(n%15==0)cout<<\"FizzBuzz\";else if(n%3==0)cout<<\"Fizz\";else if(n%5==0)cout<<\"Buzz\";else cout<<n;return 0;}",tests:[{in:"9",out:"Fizz"},{in:"10",out:"Buzz"},{in:"30",out:"FizzBuzz"},{in:"7",out:"7"}],h:["Check the 'both' case FIRST.","n%15==0 covers divisible by 3 and 5."]},
],
cpp06: [
{id:"cpp06a",t:"Array Basics",d:1,p:"Create int arr[4] = {3,1,4,1}; print the third element (index 2).",s:"#include <iostream>\nusing namespace std;\nint main() {\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int arr[4]={3,1,4,1};cout<<arr[2];return 0;}",tests:[{in:"",out:"4"}],h:["Indexing starts at 0."]},
{id:"cpp06b",t:"Sum With For",d:1,p:"Read n, then n ints. Print their sum.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int s=0;for(int i=0;i<n;i++){int x;cin>>x;s+=x;}cout<<s;return 0;}",tests:[{in:"3\n1 2 3",out:"6"},{in:"4\n5 5 5 5",out:"20"}],h:["Accumulator starts at 0.","You can read inside the loop, no array needed."]},
{id:"cpp06c",t:"Find The Max",d:2,p:"Read n, then n ints. Print the maximum.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int m;cin>>m;n--;while(n--){int x;cin>>x;if(x>m)m=x;}cout<<m;return 0;}",tests:[{in:"4\n2 9 4 7",out:"9"},{in:"1\n-5",out:"-5"}],h:["Initialize max to the FIRST element, not 0 (negatives!)."]},
{id:"cpp06d",t:"While Countdown",d:1,p:"Read n. Using a while loop, print n down to 1 space-separated, then 'go' (like: 3 2 1 go).",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;while(n>=1){cout<<n<<\" \";n--;}cout<<\"go\";return 0;}",tests:[{in:"3",out:"3 2 1 go"}],h:["Decrement inside the loop or it never ends."]},
{id:"cpp06e",t:"Reverse Array",d:2,p:"Read n, then n ints into an array. Print them in reverse order, space separated.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n    int a[100];\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int a[100];for(int i=0;i<n;i++)cin>>a[i];for(int i=n-1;i>=0;i--)cout<<a[i]<<(i?\" \":\"\");return 0;}",tests:[{in:"4\n1 2 3 4",out:"4 3 2 1"}],h:["Loop from n-1 down to 0.","Watch the trailing space; print space only between."]},
{id:"cpp06f",t:"Count Evens (Break/Continue)",d:2,p:"Read n, then n ints. Count evens, but STOP counting entirely if you hit a 0 (0 doesn't count). Print the count.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    int n; cin >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){int n;cin>>n;int c=0;for(int i=0;i<n;i++){int x;cin>>x;if(x==0)break;if(x%2==0)c++;}cout<<c;return 0;}",tests:[{in:"5\n2 4 0 6 8",out:"2"},{in:"3\n1 2 3",out:"1"}],h:["break exits the loop immediately.","Check for 0 before checking even."]},
]
});
