// manifest.js : the complete curriculum map.
// Sections marked ready:true have exercise modules; others are queued for future sessions
// (each session populates 5-10 sections; see CONTRIBUTING.md).
const MANIFEST = {
  tracks: {
    cpp: { name: "C++", sections: [
      {id:"cpp01",n:"Welcome To C++",ready:true},
      {id:"cpp02",n:"Variables",ready:true},
      {id:"cpp03",n:"Calculations With Numbers",ready:true},
      {id:"cpp04",n:"Functions I",ready:true},
      {id:"cpp05",n:"Conditional Statements",ready:true},
      {id:"cpp06",n:"Arrays & Loops",ready:true},
      {id:"cpp07",n:"Calculations - Challenges",ready:true},
      {id:"cpp08",n:"Strings I",ready:true},
      {id:"cpp09",n:"Conditional Challenges",ready:true},
      {id:"cpp10",n:"While & For Loops Deep",ready:true},
      {id:"cpp11",n:"Loops & Conditionals",ready:true},
      {id:"cpp12",n:"Looping Over Indices",ready:true},
      {id:"cpp13",n:"Big O Notation"},
      {id:"cpp14",n:"Loop Challenges"},
      {id:"cpp15",n:"Strings II"},
      {id:"cpp16",n:"Functions & Classes"},
      {id:"cpp17",n:"Pointers & References"},
      {id:"cpp18",n:"Memory & RAII"},
      {id:"cpp19",n:"STL Containers"},
      {id:"cpp20",n:"Nested Loops & Brute Force"},
      {id:"cpp21",n:"Sorting"},
      {id:"cpp22",n:"Partial Sums I"},
      {id:"cpp23",n:"Partial Sums II"},
      {id:"cpp24",n:"Two Pointers"},
      {id:"cpp25",n:"Hash Table"},
      {id:"cpp26",n:"Binary Search"},
      {id:"cpp27",n:"Recursion"},
      {id:"cpp28",n:"Divide And Conquer"},
      {id:"cpp29",n:"Backtracking"},
      {id:"cpp30",n:"Memoization"},
      {id:"cpp31",n:"Linked Lists"},
      {id:"cpp32",n:"Sliding Window"},
      {id:"cpp33",n:"Heap"},
      {id:"cpp34",n:"Stack"},
      {id:"cpp35",n:"Binary Trees"},
      {id:"cpp36",n:"Dynamic Programming"},
      {id:"cpp37",n:"Greedy"},
      {id:"cpp38",n:"Graphs"},
      {id:"cpp39",n:"Resume Level: Modern C++ (move, smart ptrs, templates)"},
      {id:"cpp40",n:"Resume Level: Concurrency & Atomics"},
    ]},
    py: { name: "Python", sections: [
      {id:"py01",n:"Welcome To Python",ready:true},
      {id:"py02",n:"Variables & Types",ready:true},
      {id:"py03",n:"Numbers & Calculations",ready:true},
      {id:"py04",n:"Functions I",ready:true},
      {id:"py05",n:"Conditional Statements",ready:true},
      {id:"py06",n:"Lists & Loops",ready:true},
      {id:"py07",n:"Strings Deep"},
      {id:"py08",n:"Dicts & Sets"},
      {id:"py09",n:"Comprehensions"},
      {id:"py10",n:"Functions II (args, lambdas, closures)"},
      {id:"py11",n:"Big O Notation"},
      {id:"py12",n:"Sorting"},
      {id:"py13",n:"Two Pointers"},
      {id:"py14",n:"Hash Table Patterns"},
      {id:"py15",n:"Binary Search"},
      {id:"py16",n:"Recursion"},
      {id:"py17",n:"Backtracking"},
      {id:"py18",n:"Memoization & DP"},
      {id:"py19",n:"Linked Lists"},
      {id:"py20",n:"Sliding Window"},
      {id:"py21",n:"Stack & Queue"},
      {id:"py22",n:"Heap"},
      {id:"py23",n:"Binary Trees"},
      {id:"py24",n:"Graphs"},
      {id:"py25",n:"Greedy"},
      {id:"py26",n:"OOP & Dunder Methods"},
      {id:"py27",n:"Files, JSON & Errors"},
      {id:"py28",n:"NumPy Fundamentals"},
      {id:"py29",n:"Pandas Fundamentals"},
      {id:"py30",n:"Resume Level: ML Pipeline Patterns (GUARD-grade)"},
      {id:"py31",n:"Resume Level: Async & Tooling"},
    ]},
    fw: { name: "Firmware / Embedded", sections: [
      {id:"fw01",n:"Bit Manipulation Bootcamp",ready:true},
      {id:"fw02",n:"C for Firmware (volatile, const, storage)"},
      {id:"fw03",n:"Registers & GPIO Patterns"},
      {id:"fw04",n:"Interrupts & ISRs"},
      {id:"fw05",n:"Timers & PWM"},
      {id:"fw06",n:"UART / SPI / I2C"},
      {id:"fw07",n:"State Machines"},
      {id:"fw08",n:"Memory Maps & Linkers"},
      {id:"fw09",n:"Debugging & Fault Analysis"},
      {id:"fw10",n:"RTOS Concepts"},
      {id:"fw11",n:"Low Power Design"},
      {id:"fw12",n:"Drivers & HALs"},
      {id:"fw13",n:"Resume Level: BLE Stack (TremorMonitor-grade)"},
      {id:"fw14",n:"Resume Level: Sensor Pipelines & DSP Basics"},
    ]},
    hw: { name: "Hardware", sections: [
      {id:"hw01",n:"Digital Logic & Number Systems"},
      {id:"hw02",n:"Combinational & Sequential Circuits"},
      {id:"hw03",n:"Circuit Analysis Refresh"},
      {id:"hw04",n:"Verilog / FPGA Intro"},
      {id:"hw05",n:"ADC/DAC & Signal Chain"},
      {id:"hw06",n:"PCB & Schematic Reading"},
      {id:"hw07",n:"Sensors & Actuators"},
      {id:"hw08",n:"Power & Batteries"},
      {id:"hw09",n:"Resume Level: Radar Sensing Concepts (GUARD-grade)"},
    ]},
    ds: { name: "Data / SQL", sections: [
      {id:"ds01",n:"SQL Fundamentals"},
      {id:"ds02",n:"Joins & Aggregations"},
      {id:"ds03",n:"Window Functions"},
      {id:"ds04",n:"Data Modeling"},
      {id:"ds05",n:"Pipelines & ETL Concepts"},
    ]},
    ai: { name: "AI / ML", sections: [
      {id:"ai01",n:"ML Fundamentals & Metrics"},
      {id:"ai02",n:"Train/Val/Test Discipline (session leakage!)"},
      {id:"ai03",n:"Classical Models"},
      {id:"ai04",n:"Neural Nets & Backprop"},
      {id:"ai05",n:"GANs & Generative (GUARD-grade)"},
      {id:"ai06",n:"ML System Design"},
    ]},
  },
  roles: {
    "Firmware Engineer": ["fw","cpp"],
    "Hardware Engineer": ["hw","fw"],
    "Software Engineer": ["cpp","py"],
    "AI Engineer": ["py","ai"],
    "Data Engineer": ["py","ds"],
  }
};
