// py-core.js : populated Python sections (run via Pyodide) + firmware seed (C via interpreter)
window.SECTIONS = window.SECTIONS || {};
Object.assign(window.SECTIONS, {
py01: [
{id:"py01a",t:"Hello, Murim",d:1,p:"Print exactly: Hello, World!",s:"# your code\n",sol:"print(\"Hello, World!\")",tests:[{in:"",out:"Hello, World!"}],h:["print() outputs text.","Strings use quotes."]},
{id:"py01b",t:"Two Lines",d:1,p:"Print 'Python' on the first line and 'is readable' on the second.",s:"",sol:"print(\"Python\")\nprint(\"is readable\")",tests:[{in:"",out:"Python\nis readable"}],h:["Each print() ends the line by default."]},
{id:"py01c",t:"Comments Don't Run",d:1,p:"Starter prints WRONG then clean. Comment out the bad line so only 'clean' prints.",s:"print(\"WRONG\")\nprint(\"clean\")",sol:"# print(\"WRONG\")\nprint(\"clean\")",tests:[{in:"",out:"clean"}],h:["# comments out a line."]},
{id:"py01d",t:"f-strings",d:1,p:"Given level = 9 in the starter, use an f-string to print: Level 9 warrior",s:"level = 9\n# print using an f-string\n",sol:"level = 9\nprint(f\"Level {level} warrior\")",tests:[{in:"",out:"Level 9 warrior"}],h:["f\"text {variable} text\""]},
{id:"py01e",t:"Fix The Crash",d:2,p:"This code crashes (bad quote and wrong name). Fix it to print: fixed",s:"prnt(\"fixed)",sol:"print(\"fixed\")",tests:[{in:"",out:"fixed"}],h:["Function is print.","Close the quote."]},
],
py02: [
{id:"py02a",t:"Assign And Print",d:1,p:"Create qi = 42 and print it.",s:"",sol:"qi = 42\nprint(qi)",tests:[{in:"",out:"42"}],h:["name = value"]},
{id:"py02b",t:"Types Tour",d:1,p:"Print on 3 lines: int 7, float 3.5, string H.",s:"",sol:"print(7)\nprint(3.5)\nprint(\"H\")",tests:[{in:"",out:"7\n3.5\nH"}],h:["Python floats print as 3.5 directly."]},
{id:"py02c",t:"Read Input",d:1,p:"Read one integer from input and print: You entered X",s:"x = int(input())\n",sol:"x = int(input())\nprint(f\"You entered {x}\")",tests:[{in:"5",out:"You entered 5"},{in:"-3",out:"You entered -3"}],h:["input() returns a string; int() converts."]},
{id:"py02d",t:"Swap, Pythonically",d:2,p:"Read two ints on one line (space separated), swap them the Python way, print 'a b' after swapping.",s:"a, b = map(int, input().split())\n",sol:"a, b = map(int, input().split())\na, b = b, a\nprint(a, b)",tests:[{in:"1 2",out:"2 1"},{in:"9 9",out:"9 9"}],h:["a, b = b, a  (no temp needed)","print(a, b) space-separates automatically."]},
{id:"py02e",t:"Casting Chain",d:2,p:"Read a float, convert to int (truncating), then to string, and print the string twice concatenated (e.g. 7.9 -> '77').",s:"x = float(input())\n",sol:"x = float(input())\ns = str(int(x))\nprint(s + s)",tests:[{in:"7.9",out:"77"},{in:"12.1",out:"1212"}],h:["int(7.9) is 7 (truncates).","'7' + '7' concatenates strings."]},
],
py03: [
{id:"py03a",t:"Arithmetic Operators",d:1,p:"Read two ints (two lines). Print sum, difference, product on 3 lines.",s:"a = int(input())\nb = int(input())\n",sol:"a = int(input())\nb = int(input())\nprint(a+b)\nprint(a-b)\nprint(a*b)",tests:[{in:"6\n3",out:"9\n3\n18"}],h:["One print per line of output."]},
{id:"py03b",t:"Area Of Rectangle",d:1,p:"Read width and height (one line, space separated). Print the area.",s:"w, h = map(int, input().split())\n",sol:"w, h = map(int, input().split())\nprint(w*h)",tests:[{in:"4 5",out:"20"}],h:["area = w * h"]},
{id:"py03c",t:"Find Discount",d:2,p:"Read price (float) and percent (int) on one line. Print the discount amount. If it's a whole number print it like 20.0 (default float formatting).",s:"parts = input().split()\nprice, pct = float(parts[0]), int(parts[1])\n",sol:"parts = input().split()\nprice, pct = float(parts[0]), int(parts[1])\nprint(price*pct/100)",tests:[{in:"200 10",out:"20.0"},{in:"50 50",out:"25.0"}],h:["float math gives 20.0, that's expected here."]},
{id:"py03d",t:"True Division vs Floor",d:2,p:"Read two ints a b. Print a/b then a//b on two lines.",s:"a, b = map(int, input().split())\n",sol:"a, b = map(int, input().split())\nprint(a/b)\nprint(a//b)",tests:[{in:"7 2",out:"3.5\n3"},{in:"8 4",out:"2.0\n2"}],h:["/ always gives float; // floors."]},
{id:"py03e",t:"Hours And Mins Into Seconds",d:1,p:"Read hours and minutes (one line). Print total seconds.",s:"h, m = map(int, input().split())\n",sol:"h, m = map(int, input().split())\nprint(h*3600 + m*60)",tests:[{in:"1 30",out:"5400"}],h:["3600 seconds per hour."]},
{id:"py03f",t:"Modulo Clock",d:2,p:"Read total minutes. Print 'H hours M minutes'.",s:"t = int(input())\n",sol:"t = int(input())\nprint(f\"{t//60} hours {t%60} minutes\")",tests:[{in:"135",out:"2 hours 15 minutes"},{in:"59",out:"0 hours 59 minutes"}],h:["// for hours, % for leftover minutes."]},
{id:"py03g",t:"Free Coffee Cups",d:2,p:"1 free coffee per 5 stamps. Read stamps; print free coffees and leftover stamps, space separated.",s:"s = int(input())\n",sol:"s = int(input())\nprint(s//5, s%5)",tests:[{in:"12",out:"2 2"},{in:"4",out:"0 4"}],h:["print(a, b) handles the space."]},
{id:"py03h",t:"Augmented Assignment",d:2,p:"Start x = 10. Apply: x += 5, x *= 2, x -= 1. Print x.",s:"x = 10\n",sol:"x = 10\nx += 5\nx *= 2\nx -= 1\nprint(x)",tests:[{in:"",out:"29"}],h:["Python has no x++ ; use x += 1 style."]},
],
py04: [
{id:"py04a",t:"First Function",d:1,p:"Define greet() that prints 'ready'. Call it.",s:"# define greet, then call it\n",sol:"def greet():\n    print(\"ready\")\n\ngreet()",tests:[{in:"",out:"ready"}],h:["def name():, indent the body."]},
{id:"py04b",t:"Parameters",d:1,p:"Define shout(n) printing 'HA' n times on one line. Read n and call it.",s:"def shout(n):\n    pass\n\nn = int(input())\nshout(n)",sol:"def shout(n):\n    print(\"HA\"*n)\n\nn = int(input())\nshout(n)",tests:[{in:"3",out:"HAHAHA"}],h:["String repetition: \"HA\"*n."]},
{id:"py04c",t:"Return Values",d:1,p:"Define square(x) returning x*x. Read x, print square(x).",s:"def square(x):\n    pass\n\nx = int(input())\nprint(square(x))",sol:"def square(x):\n    return x*x\n\nx = int(input())\nprint(square(x))",tests:[{in:"6",out:"36"},{in:"-4",out:"16"}],h:["return, not print, inside the function."]},
{id:"py04d",t:"Default Arguments",d:2,p:"Define power(base, exp=2) returning base**exp. Read one int b, print power(b) then power(b,3) on two lines.",s:"def power(base, exp=2):\n    pass\n\nb = int(input())\n",sol:"def power(base, exp=2):\n    return base**exp\n\nb = int(input())\nprint(power(b))\nprint(power(b,3))",tests:[{in:"2",out:"4\n8"},{in:"3",out:"9\n27"}],h:["exp=2 in the signature sets the default."]},
{id:"py04e",t:"Multiple Returns",d:2,p:"Define minmax(a,b,c) returning (smallest, largest) as a tuple. Read three ints one line, print 'min max'.",s:"def minmax(a,b,c):\n    pass\n\na,b,c = map(int, input().split())\nlo, hi = minmax(a,b,c)\nprint(lo, hi)",sol:"def minmax(a,b,c):\n    return min(a,b,c), max(a,b,c)\n\na,b,c = map(int, input().split())\nlo, hi = minmax(a,b,c)\nprint(lo, hi)",tests:[{in:"3 9 5",out:"3 9"}],h:["return x, y returns a tuple.","Built-ins min() and max() are allowed."]},
{id:"py04f",t:"Buy Candy (Challenge)",d:2,p:"Candy costs 3 coins. Define candies(coins). Read coins, print candies(coins).",s:"def candies(coins):\n    pass\n\nc = int(input())\nprint(candies(c))",sol:"def candies(coins):\n    return coins//3\n\nc = int(input())\nprint(candies(c))",tests:[{in:"10",out:"3"},{in:"2",out:"0"}],h:["Floor division."]},
],
py05: [
{id:"py05a",t:"If",d:1,p:"Read an int. If greater than 100, print 'big'. Else print nothing.",s:"x = int(input())\n",sol:"x = int(input())\nif x > 100:\n    print(\"big\")",tests:[{in:"150",out:"big"},{in:"7",out:""}],h:["Colon then indented block."]},
{id:"py05b",t:"If / Else",d:1,p:"Read an int. Print 'even' or 'odd'.",s:"x = int(input())\n",sol:"x = int(input())\nprint(\"even\" if x%2==0 else \"odd\")",tests:[{in:"4",out:"even"},{in:"9",out:"odd"}],h:["x % 2 == 0 tests even."]},
{id:"py05c",t:"Elif Ladder",d:2,p:"Read score 0-100. Print A (>=90), B (>=80), C (>=70), else F.",s:"s = int(input())\n",sol:"s = int(input())\nif s>=90: print(\"A\")\nelif s>=80: print(\"B\")\nelif s>=70: print(\"C\")\nelse: print(\"F\")",tests:[{in:"91",out:"A"},{in:"80",out:"B"},{in:"42",out:"F"}],h:["elif, highest threshold first."]},
{id:"py05d",t:"Logical Operators",d:2,p:"Read age and has_ticket (0/1) on one line. Print 'enter' if age>=18 and ticket==1 else 'denied'.",s:"age, t = map(int, input().split())\n",sol:"age, t = map(int, input().split())\nprint(\"enter\" if age>=18 and t==1 else \"denied\")",tests:[{in:"20 1",out:"enter"},{in:"15 1",out:"denied"}],h:["and / or / not are words in Python."]},
{id:"py05e",t:"FizzBuzz Single",d:2,p:"Read one int. Fizz if %3, Buzz if %5, FizzBuzz if both, else the number.",s:"n = int(input())\n",sol:"n = int(input())\nif n%15==0: print(\"FizzBuzz\")\nelif n%3==0: print(\"Fizz\")\nelif n%5==0: print(\"Buzz\")\nelse: print(n)",tests:[{in:"9",out:"Fizz"},{in:"10",out:"Buzz"},{in:"30",out:"FizzBuzz"},{in:"7",out:"7"}],h:["Both-case first: n%15."]},
],
py06: [
{id:"py06a",t:"List Basics",d:1,p:"Create arr = [3,1,4,1] and print the third element (index 2).",s:"",sol:"arr = [3,1,4,1]\nprint(arr[2])",tests:[{in:"",out:"4"}],h:["Zero-indexed."]},
{id:"py06b",t:"Sum With For",d:1,p:"Read n, then a line with n ints. Print their sum (without using sum()).",s:"n = int(input())\nnums = list(map(int, input().split()))\n",sol:"n = int(input())\nnums = list(map(int, input().split()))\ns = 0\nfor x in nums:\n    s += x\nprint(s)",tests:[{in:"3\n1 2 3",out:"6"}],h:["Accumulator pattern.","for x in nums:"]},
{id:"py06c",t:"Find The Max",d:2,p:"Read n, then n ints on one line. Print the max WITHOUT using max().",s:"n = int(input())\nnums = list(map(int, input().split()))\n",sol:"n = int(input())\nnums = list(map(int, input().split()))\nm = nums[0]\nfor x in nums:\n    if x > m: m = x\nprint(m)",tests:[{in:"4\n2 9 4 7",out:"9"},{in:"1\n-5",out:"-5"}],h:["Seed with the first element, not 0."]},
{id:"py06d",t:"While Countdown",d:1,p:"Read n. While loop printing n down to 1 space separated, then 'go' (one line, like: 3 2 1 go).",s:"n = int(input())\n",sol:"n = int(input())\nout = []\nwhile n >= 1:\n    out.append(str(n))\n    n -= 1\nout.append(\"go\")\nprint(\" \".join(out))",tests:[{in:"3",out:"3 2 1 go"}],h:["Collect pieces then ' '.join, or print(x, end=' ')."]},
{id:"py06e",t:"Reverse A List",d:2,p:"Read n then n ints on one line. Print them reversed, space separated, using a loop or slicing.",s:"n = int(input())\nnums = list(map(int, input().split()))\n",sol:"n = int(input())\nnums = list(map(int, input().split()))\nprint(\" \".join(map(str, nums[::-1])))",tests:[{in:"4\n1 2 3 4",out:"4 3 2 1"}],h:["nums[::-1] reverses.","join needs strings: map(str, ...)."]},
{id:"py06f",t:"Count Evens With Break",d:2,p:"Read n then n ints. Count evens but stop entirely at the first 0 (0 doesn't count). Print the count.",s:"n = int(input())\nnums = list(map(int, input().split()))\n",sol:"n = int(input())\nnums = list(map(int, input().split()))\nc = 0\nfor x in nums:\n    if x == 0: break\n    if x % 2 == 0: c += 1\nprint(c)",tests:[{in:"5\n2 4 0 6 8",out:"2"},{in:"3\n1 2 3",out:"1"}],h:["break before the even check."]},
],
// ---- firmware seed: pure-C exercises runnable in the interpreter ----
fw01: [
{id:"fw01a",t:"Set A Bit",d:1,p:"Read a byte value and bit position n. Print the value with bit n SET. (C, use unsigned int.)",s:"#include <iostream>\nusing namespace std;\nint main() {\n    unsigned int v, n;\n    cin >> v >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){unsigned int v,n;cin>>v>>n;cout<<(v|(1u<<n));return 0;}",tests:[{in:"8 0",out:"9"},{in:"0 3",out:"8"}],h:["OR with a shifted 1: v | (1u << n)"]},
{id:"fw01b",t:"Clear A Bit",d:1,p:"Read value and bit n. Print value with bit n CLEARED.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    unsigned int v, n;\n    cin >> v >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){unsigned int v,n;cin>>v>>n;cout<<(v&~(1u<<n));return 0;}",tests:[{in:"15 1",out:"13"},{in:"8 3",out:"0"}],h:["AND with the inverted mask: v & ~(1u<<n)"]},
{id:"fw01c",t:"Toggle And Check",d:2,p:"Read value and bit n. Print the toggled value, then on the next line print 1 if bit n was originally set, else 0.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    unsigned int v, n;\n    cin >> v >> n;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){unsigned int v,n;cin>>v>>n;cout<<(v^(1u<<n))<<\"\\n\"<<((v>>n)&1u);return 0;}",tests:[{in:"5 0",out:"4\n1"},{in:"4 1",out:"6\n0"}],h:["XOR toggles.","(v >> n) & 1 isolates the bit."]},
{id:"fw01d",t:"Count Set Bits (Kernighan)",d:2,p:"Read an unsigned int. Print the number of set bits using the v &= v-1 trick.",s:"#include <iostream>\nusing namespace std;\nint main() {\n    unsigned int v;\n    cin >> v;\n\n    return 0;\n}",sol:"#include <iostream>\nusing namespace std;\nint main(){unsigned int v;cin>>v;int c=0;while(v){v&=v-1;c++;}cout<<c;return 0;}",tests:[{in:"7",out:"3"},{in:"1024",out:"1"},{in:"0",out:"0"}],h:["Each v &= v-1 clears the lowest set bit.","Loop while v != 0."]},
]
});
